# Definitions for jobs that run periodically.  For details on the format, see
# `taskcluster/taskgraph/cron/schema.py`.  For documentation, see
# `taskcluster/docs/cron.rst`.
---

jobs:
    - name: snapshot
      job:
          type: decision-task
          treeherder-symbol: snapshot-D
          target-tasks-method: snapshot
      when:
          - {hour: 13, minute: 0}
          - {hour: 19, minute: 0}
    - name: nightly
      job:
          type: decision-task
          treeherder-symbol: nightly-D
          target-tasks-method: nightly
      when:
          - {hour: 13, minute: 0}
          - {hour: 19, minute: 0}
