pull_request_rules:
  - name: Resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request has conflicts when rebasing. Could you fix it @{{author}}? 🙏
  - name: MickeyMoz - Auto Merge
    conditions:
      - author=MickeyMoz
      - status-success=complete-pr
      - files~=(Gecko.kt|publicsuffixes)
    actions:
      review:
        type: APPROVE
        message: MickeyMoz 💪
      merge:
        method: rebase
        # These PRs are just bumping version or updating suffixes,
        # and very unlikely to break anything. It's not worth the delay
        # of rebasing them (sometimes multiple times) before merging.
        strict: false
  - name: L10N - Auto Merge
    conditions:
      - author=mozilla-l10n-automation-bot
      - status-success=complete-pr
      - files~=(strings.xml|l10n.toml)
    actions:
      review:
        type: APPROVE
        message: LGTM 😎
      merge:
        method: rebase
        # These PRs are just bumping version or updating suffixes,
        # and very unlikely to break anything. It's not worth the delay
        # of rebasing them (sometimes multiple times) before merging.
        strict: false
  - name: Release automation
    conditions:
      - author=github-actions[bot]
      - status-success=complete-pr
      - files~=(.buildconfig.yml|Gecko.kt)
    actions:
      review:
        type: APPROVE
        message: 🚢
      merge:
        method: rebase
        strict: smart
      delete_head_branch:
        force: false
  - name: Needs landing - Rebase
    conditions:
      - status-success=complete-pr
      - label=🛬 needs landing
      - "#approved-reviews-by>=1"
      - -draft
      - label!=work in progress
      - label!=do not land
    actions:
      merge:
        method: rebase
        strict: smart
  - name: Needs landing - Squash
    conditions:
      - status-success=complete-pr
      - label=🛬 needs landing (squash)
      - "#approved-reviews-by>=1"
      - -draft
      - label!=work in progress
      - label!=do not land
    actions:
      merge:
        method: squash
        strict: smart
