language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.2
    - android-28

sudo: false

before_install:
  - touch local.properties
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew --no-daemon clean test -Pcoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

