---
trust-domain: mobile
treeherder:
    group-names:
        I: Docker Image Builds
        # Groups are generated off buildconfig.yml, except these ones:
        samples-browser-beta: samples-browser-beta
        samples-browser-release: samples-browser-release
        samples-browser-system: samples-browser-system
        # These ones are too long to fit in 25 chars
        browser-engine-gecko-nigh: browser-engine-gecko-nightly
        lib-fetch-httpurlconnect: lib-fetch-httpurlconnection

task-priority: highest

taskgraph:
    register: ac_taskgraph:register
    repositories:
        mobile:
            name: android-components
    cached-task-prefix: project.mobile.android-components
    decision-parameters: 'ac_taskgraph:get_decision_parameters'

workers:
    aliases:
        b-android:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: b-linux-large
        images:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: images
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: mobile-t-signing
        signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type:
                by-level:
                    "3": mobile-3-signing
                    default: mobile-t-signing
        beetmover:
            provisioner: scriptworker-k8s
            implementation: scriptworker-beetmover
            os: scriptworker
            worker-type: 'mobile-{level}-beetmover'

scriptworker:
    scope-prefix: project:mobile:android-components:releng
