# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.transform:loader

transforms:
    - ac_taskgraph.transforms.build:transforms
    - taskgraph.transforms.code_review:transforms
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms



job-defaults:
    attributes:
        build-type: regular
        code-review: true
        component: samples-browser
    description: Execute Gradle tasks for component "{component}"
    include-coverage: true
    run:
        using: gradlew
        use-caches: false
    run-on-tasks-for: [github-pull-request, github-push]
    treeherder:
        kind: build
        platform: android-all/opt
        tier: 1
    worker-type: b-android
    worker:
        chain-of-trust: true
        docker-image: {in-tree: base}
        max-run-time: 7200

jobs:
    nightly:
        run:
            gradlew:
                - ':samples-browser:assembleGeckoNightly'
                - ':samples-browser:testGeckoNightlyDebugUnitTest'
                - ':samples-browser:lintGeckoNightly'
        treeherder:
            symbol: 'samples-browser(B)'
    beta:
        run:
            gradlew:
                - ':samples-browser:assembleGeckoBeta'
                - ':samples-browser:testGeckoBetaDebugUnitTest'
        treeherder:
            symbol: 'samples-browser-beta(B)'

    release:
        run:
            gradlew:
                - ':samples-browser:assembleGeckoRelease'
                - ':samples-browser:testGeckoReleaseDebugUnitTest'
        treeherder:
            symbol: 'samples-browser-release(B)'

    system:
        run:
            gradlew: [':samples-browser:assembleSystem']
        treeherder:
            symbol: 'samples-browser-system(B)'
