# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mozilla Android Components
# email: android-components@lists.mozilla.org
description: >- # this means to ignore newlines until "baseurl:"
   A collection of Android libraries to build browsers or browser-like applications.
# baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mozac.org/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: anti_hype
#github_username:  mozilla-mobile

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
# theme: jekyll-whiteglass

plugins:
  - jekyll-feed

header_pages:
  - components.md
  - changelog.md
  - reference.md
  - blog.md
  - contributing.md

